# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oai_kpa_stm_widget_qt.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1089, 498)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.line_10 = QtWidgets.QFrame(Form)
        self.line_10.setMinimumSize(QtCore.QSize(0, 10))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 5, 2, 1, 1)
        self.corePartGLayout = QtWidgets.QGridLayout()
        self.corePartGLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.corePartGLayout.setObjectName("corePartGLayout")
        self.moduleSerialNumberLEdit = QtWidgets.QLineEdit(Form)
        self.moduleSerialNumberLEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleSerialNumberLEdit.sizePolicy().hasHeightForWidth())
        self.moduleSerialNumberLEdit.setSizePolicy(sizePolicy)
        self.moduleSerialNumberLEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.moduleSerialNumberLEdit.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.moduleSerialNumberLEdit.setText("")
        self.moduleSerialNumberLEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.moduleSerialNumberLEdit.setObjectName("moduleSerialNumberLEdit")
        self.corePartGLayout.addWidget(self.moduleSerialNumberLEdit, 1, 1, 1, 1)
        self.connectionPButton = QtWidgets.QPushButton(Form)
        self.connectionPButton.setEnabled(True)
        self.connectionPButton.setMinimumSize(QtCore.QSize(150, 30))
        self.connectionPButton.setMaximumSize(QtCore.QSize(2000, 30))
        self.connectionPButton.setFlat(False)
        self.connectionPButton.setObjectName("connectionPButton")
        self.corePartGLayout.addWidget(self.connectionPButton, 1, 2, 1, 1)
        self.statusLineEdit = QtWidgets.QLineEdit(Form)
        self.statusLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.statusLineEdit.setObjectName("statusLineEdit")
        self.corePartGLayout.addWidget(self.statusLineEdit, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.corePartGLayout, 6, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.singleReadPushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleReadPushButton.sizePolicy().hasHeightForWidth())
        self.singleReadPushButton.setSizePolicy(sizePolicy)
        self.singleReadPushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.singleReadPushButton.setMaximumSize(QtCore.QSize(200, 30))
        self.singleReadPushButton.setObjectName("singleReadPushButton")
        self.gridLayout_3.addWidget(self.singleReadPushButton, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(200, 682, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 1)
        self.cycleReadPushButton = QtWidgets.QPushButton(self.frame)
        self.cycleReadPushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.cycleReadPushButton.setMaximumSize(QtCore.QSize(200, 30))
        self.cycleReadPushButton.setObjectName("cycleReadPushButton")
        self.gridLayout_3.addWidget(self.cycleReadPushButton, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 4, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.stmTableWidget = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stmTableWidget.sizePolicy().hasHeightForWidth())
        self.stmTableWidget.setSizePolicy(sizePolicy)
        self.stmTableWidget.setMinimumSize(QtCore.QSize(830, 400))
        self.stmTableWidget.setMaximumSize(QtCore.QSize(830, 400))
        self.stmTableWidget.setLineWidth(2)
        self.stmTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stmTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.stmTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.stmTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.stmTableWidget.setWordWrap(False)
        self.stmTableWidget.setRowCount(8)
        self.stmTableWidget.setColumnCount(12)
        self.stmTableWidget.setObjectName("stmTableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("АЦП 1, 1-8")
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.stmTableWidget.setHorizontalHeaderItem(7, item)
        self.stmTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.stmTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.stmTableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.stmTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.stmTableWidget.horizontalHeader().setStretchLastSection(False)
        self.stmTableWidget.verticalHeader().setDefaultSectionSize(40)
        self.stmTableWidget.verticalHeader().setHighlightSections(True)
        self.stmTableWidget.verticalHeader().setMinimumSectionSize(40)
        self.stmTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.stmTableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.stmTableWidget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.moduleSerialNumberLEdit.setPlaceholderText(_translate("Form", "Serial Number"))
        self.connectionPButton.setText(_translate("Form", "Подключение"))
        self.singleReadPushButton.setText(_translate("Form", "Чтение"))
        self.cycleReadPushButton.setText(_translate("Form", "Циклический опрос"))
        item = self.stmTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Имя СТМ"))
        item = self.stmTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Имя СТМ"))
        item = self.stmTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "АЦП 1, 9-16"))
        item = self.stmTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Имя СТМ"))
        item = self.stmTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "АЦП 2, 1-8"))
        item = self.stmTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Имя СТМ"))
        item = self.stmTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "АЦП 2, 9-16"))
